# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Programming/Qt/GimbiseoUI/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(592, 723)
        Dialog.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setUnderline(True)
        font.setStrikeOut(False)
        Dialog.setFont(font)
        self.label_hm = QtWidgets.QLabel(Dialog)
        self.label_hm.setGeometry(QtCore.QRect(201, 16, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_hm.setFont(font)
        self.label_hm.setTextFormat(QtCore.Qt.RichText)
        self.label_hm.setScaledContents(True)
        self.label_hm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hm.setObjectName("label_hm")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 70, 561, 621))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_dialogue = QtWidgets.QTextEdit(self.layoutWidget)
        self.text_dialogue.setEnabled(True)
        self.text_dialogue.setMinimumSize(QtCore.QSize(0, 350))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.text_dialogue.setFont(font)
        self.text_dialogue.setReadOnly(True)
        self.text_dialogue.setObjectName("text_dialogue")
        self.verticalLayout.addWidget(self.text_dialogue)
        self.edit_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_input.setMinimumSize(QtCore.QSize(20, 30))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.edit_input.setFont(font)
        self.edit_input.setObjectName("edit_input")
        self.verticalLayout.addWidget(self.edit_input)
        self.buttons = QtWidgets.QHBoxLayout()
        self.buttons.setObjectName("buttons")
        self.button_load = QtWidgets.QPushButton(self.layoutWidget)
        self.button_load.setObjectName("button_load")
        self.buttons.addWidget(self.button_load)
        self.button_save = QtWidgets.QPushButton(self.layoutWidget)
        self.button_save.setObjectName("button_save")
        self.buttons.addWidget(self.button_save)
        self.button_quit = QtWidgets.QPushButton(self.layoutWidget)
        self.button_quit.setObjectName("button_quit")
        self.buttons.addWidget(self.button_quit)
        self.button_clear = QtWidgets.QPushButton(self.layoutWidget)
        self.button_clear.setObjectName("button_clear")
        self.buttons.addWidget(self.button_clear)
        self.button_demo = QtWidgets.QPushButton(self.layoutWidget)
        self.button_demo.setObjectName("button_demo")
        self.buttons.addWidget(self.button_demo)
        self.verticalLayout.addLayout(self.buttons)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 12, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_information = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_information.setFont(font)
        self.label_information.setObjectName("label_information")
        self.horizontalLayout_2.addWidget(self.label_information)
        self.text_information = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.text_information.setEnabled(True)
        self.text_information.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.text_information.setFont(font)
        self.text_information.setObjectName("text_information")
        self.horizontalLayout_2.addWidget(self.text_information)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_logo = QtWidgets.QLabel(Dialog)
        self.label_logo.setGeometry(QtCore.QRect(460, 10, 91, 61))
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "GIMBISEO V1.0"))
        self.label_hm.setText(_translate("Dialog", "* 人机对话系统 *"))
        self.text_dialogue.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\';\"><br /></p></body></html>"))
        self.edit_input.setPlaceholderText(_translate("Dialog", "输入语句或命令"))
        self.button_load.setText(_translate("Dialog", "载入"))
        self.button_save.setText(_translate("Dialog", "保存"))
        self.button_quit.setText(_translate("Dialog", "退出"))
        self.button_clear.setText(_translate("Dialog", "清屏"))
        self.button_demo.setText(_translate("Dialog", "演示"))
        self.label_information.setText(_translate("Dialog", "打印信息"))
